import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {applyPatch} from './helpers/settings-fixture.mjs';
const read=p=>fs.readFileSync(p,'utf8'),dir='bundles/balance-cdq/v25.22',ROOT='master_1234567890',GENERAL='1F7rgU20Hc1PmjxQHY7ALTqkqArN6RSsf',A='clientA_123456789',B='clientB_123456789',SUB='subfolder_1234567',FILE='file_pdf_12345678',F='application/vnd.google-apps.folder';
const id=n=>'copy-11111111-2222-3333-4444-'+String(n).padStart(12,'0');
function fixture(){
 const data={};function add(id,name,parent,mimeType=F){data[id]={id,name,mimeType,parents:parent?[parent]:[],trashed:false};return data[id]}
 add(ROOT,'Clients');add(GENERAL,'Drive général');add(A,'Anhydra',ROOT);add(B,'Autre client',ROOT);add(SUB,'Archives',A);add(FILE,'Balance.pdf',SUB,'application/pdf');add('sheet_1234567890','Mesures',SUB,'application/vnd.google-apps.spreadsheet');add('outside_123456789','Hors CDQ');
 const props=new Map(),calls=[];let role='admin',email='a@test.invalid',number=0,failCopy=false,locked=false;
 const drive={
  get:(id)=>{calls.push(['get',id]);if(!data[id])throw Error('Introuvable');return structuredClone(data[id]);},
  list:options=>{calls.push(['list',options.q]);let rows=Object.values(data).filter(x=>!x.trashed);const parent=options.q.match(/^'([^']+)' in parents/);if(parent)rows=rows.filter(x=>x.parents?.includes(parent[1]));const mime=options.q.match(/mimeType='([^']+)'/);if(mime)rows=rows.filter(x=>x.mimeType===mime[1]);const name=options.q.match(/and name='((?:\\.|[^'])*)'/);if(name)rows=rows.filter(x=>x.name===name[1].replace(/\\'/g,"'").replace(/\\\\/g,'\\'));const offset=+(options.pageToken||0),limit=Math.min(options.pageSize,2);return {files:structuredClone(rows.slice(offset,offset+limit)),nextPageToken:offset+limit<rows.length?String(offset+limit):''}},
  create:body=>{calls.push(['create',body.name]);const fresh='created_'+String(++number).padStart(12,'0');return structuredClone(add(fresh,body.name,body.parents[0],body.mimeType))},
  copy:(body,source)=>{calls.push(['copy',source]);if(failCopy)throw Error('Copie refusée par Drive');const fresh='created_'+String(++number).padStart(12,'0');return structuredClone(add(fresh,body.name,body.parents[0],data[source].mimeType));},
  update:(body,target)=>{calls.push(['update',target]);Object.assign(data[target],body);return data[target]}
 };
 const c=vm.createContext({console,Date,CONFIG:{MASTER_FOLDER_ID:ROOT},Drive:{Files:drive},verifierDroit_:action=>{calls.push(['auth',action]);if(!['admin','technicien'].includes(role))throw Error('Non autorisé');return {email,role};},empreinteCDQ_:s=>crypto.createHash('sha256').update(s).digest('hex'),PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>{assert.ok(v.length<9000);props.set(k,v)}})},LockService:{getScriptLock:()=>({waitLock:()=>{locked=true},releaseLock:()=>{locked=false}})},invaliderCacheContenuClient_:cid=>calls.push(['invalidate',cid]),invaliderCacheCompagnies_:()=>{},remplacerNoteCDQ_:()=>''});
 vm.runInContext(read('bundles/balance-cdq/v25.21/files/CDQDriveBrowser.gs'),c);vm.runInContext(read(dir+'/files/CDQCopy.gs'),c);
 return {c,data,calls,add,props,setRole:x=>role=x,setEmail:x=>email=x,fail:()=>failCopy=true,locked:()=>locked};
}
test('V25.22 package applies to actual V25.21 sources and pins the helper',()=>{
 const m=JSON.parse(read(dir+'/manifest.json'));assert.deepEqual(m,JSON.parse(read(dir+'/Balance_CDQ_V25_22.cdq')));assert.deepEqual(m,JSON.parse(read('bundles/balance-cdq/latest/manifest.json')));
 assert.equal(m.extraFiles[0].sha256,crypto.createHash('sha256').update(read(dir+'/files/CDQCopy.gs')).digest('hex'));
 for(const name of ['feedback','copy','desktop']){new vm.Script(read(dir+'/'+name+'.js'));assert.ok(m.patches.some(p=>p.replacement?.includes(read(dir+'/'+name+'.js'))));}
 if(process.env.CDQ_V2521_SOURCE)for(const file of ['Selector.html','Code.gs']){let s=read(process.env.CDQ_V2521_SOURCE+'-'+file);for(const p of m.patches.filter(x=>x.file===file))s=applyPatch(s,p);fs.writeFileSync('/tmp/cdq-v2522-'+file,s);if(file==='Code.gs')new vm.Script(s);else for(const b of s.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!b[1].includes('application/json'))new vm.Script(b[2]);}
});
test('Writer authorization happens before any reads or writes',()=>{const f=fixture();f.setRole('lecture');assert.throws(()=>f.c.copierElementCDQV2522(FILE,SUB,id(1)),/autorisé/);assert.deepEqual(f.calls,[['auth','ecriture']]);});
test('Copy file in its current folder keeps original; request retries do not duplicate',()=>{const f=fixture(),original=structuredClone(f.data[FILE]);const result=f.c.copierElementCDQV2522(FILE,SUB,id(1));assert.equal(result.nom,'Balance - Copie.pdf');assert.equal(result.clientId,A);assert.equal(f.data[result.id].parents[0],SUB);assert.deepEqual(f.data[FILE],original);assert.equal(f.c.copierElementCDQV2522(FILE,SUB,id(1)).id,result.id);assert.equal(f.calls.filter(x=>x[0]==='copy').length,1);assert.equal(f.locked(),false);const next=f.c.copierElementCDQV2522(FILE,SUB,id(2));assert.equal(next.nom,'Balance - Copie 2.pdf');assert.throws(()=>f.c.copierElementCDQV2522(FILE,B,id(1)),/destination/);});
test('Nested folder copy includes empty folders, binary and Sheets files across clients',()=>{const f=fixture();f.add('empty_1234567890','Vide',SUB);const result=f.c.copierElementCDQV2522(SUB,B,id(1));assert.equal(result.kind,'folder');assert.equal(result.copiedItems,4);const children=Object.values(f.data).filter(x=>x.parents[0]===result.id);assert.deepEqual(children.map(x=>x.name).sort(),['Balance.pdf','Mesures','Vide']);assert.equal(f.data[result.id].parents[0],B);assert.equal(f.calls.some(x=>x[0]==='invalidate'&&x[1]===B),true);});
test('Invalid roots, out-of-scope items, descendants and shortcuts fail before writes',()=>{for(const [source,dest] of [[ROOT,A],[SUB,SUB],[SUB,'empty_1234567890'],['outside_123456789',A],[FILE,GENERAL]]){const f=fixture();f.add('empty_1234567890','Enfant',SUB);assert.throws(()=>f.c.copierElementCDQV2522(source,dest,id(1)));assert.equal(f.calls.some(x=>['copy','create'].includes(x[0])),false);}const f=fixture();f.add('shortcut_12345678','Lien',SUB,'application/vnd.google-apps.shortcut');assert.throws(()=>f.c.copierElementCDQV2522(SUB,B,id(1)),/raccourci/);assert.equal(f.calls.some(x=>x[0]==='create'),false);});
test('Failed folder copy removes only its new partial root; original stays intact',()=>{const f=fixture();f.fail();assert.throws(()=>f.c.copierElementCDQV2522(SUB,B,id(1)),/interrompue/);assert.equal(f.data[SUB].trashed,false);assert.equal(f.data[FILE].trashed,false);const created=Object.values(f.data).filter(x=>x.id.startsWith('created_'));assert.equal(created.length,1);assert.equal(created[0].trashed,true);assert.throws(()=>f.c.copierElementCDQV2522(SUB,B,id(1)),/interrompue/);assert.equal(f.locked(),false);});
test('Context uses actual immediate parent and destination list includes all pages',()=>{const f=fixture();for(let i=0;i<8;i++)f.add('folder_'+String(i).padStart(12,'0'),'Dossier '+i,B);assert.equal(f.c.obtenirContexteCopieCDQV2522(FILE).parentId,SUB);assert.equal(f.c.obtenirDossiersCopieCDQV2522(B,FILE).items.length,8);assert.throws(()=>f.c.obtenirDossiersCopieCDQV2522(SUB,SUB),/intérieur/);});
test('Oversized folder is refused before creating any partial destination',()=>{const f=fixture();for(let i=0;i<201;i++)f.add('file_'+String(i).padStart(12,'0'),'Rapport '+i,SUB,'application/pdf');assert.throws(()=>f.c.copierElementCDQV2522(SUB,B,id(1)),/volumineux/);assert.equal(f.calls.some(x=>x[0]==='create'||x[0]==='copy'),false);});
