import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import puppeteer from 'puppeteer-core';import {applyPatch} from './helpers/settings-fixture.mjs';
const read=p=>fs.readFileSync(p,'utf8'),bundle=JSON.parse(read('bundles/balance-cdq/v25.25/manifest.json'));
let share=read('tests/fixtures/share-v2524.html');for(const p of bundle.patches.filter(p=>p.id?.startsWith('share-')))share=applyPatch(share,p);
const full=process.env.CDQ_V2525_SELECTOR?read(process.env.CDQ_V2525_SELECTOR):'';
const css=full?[...full.matchAll(/<style\b[^>]*>[\s\S]*?<\/style>/gi)].map(m=>m[0]).join(''):'<style>'+read('bundles/balance-cdq/v25.18/desktop.css')+read('bundles/balance-cdq/v25.24/interface.css')+read('bundles/balance-cdq/v25.25/interface.css')+'</style>';
const sharePage='<!doctype html><html class="windows"><meta charset="utf-8">'+css+'<style>.modal-overlay{position:fixed;inset:0;z-index:420000;align-items:center;justify-content:center;background:#0008}.modal{background:#102a40;padding:20px;max-width:640px;max-height:90vh;overflow:auto}#openShare,#testAction{position:fixed;top:10px;left:10px;z-index:400001}#testAction{left:240px}</style><body><main><button id="testAction" onclick="window.clicks=(window.clicks||0)+1">Action</button><button id="openShare" onclick="cdqOuvrirPartageApplication()">Partager</button></main><div id="cdqPcV16"><nav class="pc16-nav"><button class="active">Accueil</button></nav></div>'+share+'</body></html>';
const server=http.createServer((req,res)=>{const path=new URL(req.url,'http://local').pathname.slice(1);if(path==='share'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end(sharePage)}if(path==='host'){res.setHeader('Content-Type','text/html;charset=utf-8');return res.end('<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><button id="open">PDF</button><script type="module">import {openReader} from "/reader-host-v2525.mjs";document.getElementById("open").onclick=async()=>openReader({blob:await(await fetch("/server.pdf")).blob(),name:"Balance QA.pdf",fileId:"pdf_test",onSave:async b=>{window.saved=b;return {queued:true}}});</script>')}
let f=path==='server.pdf'?'/tmp/cdq-v2525-server.pdf':path;if(f.includes('..')||!fs.existsSync(f)||!fs.statSync(f).isFile()){res.statusCode=404;return res.end()}res.setHeader('Content-Type',/\.(mjs|js)$/.test(f)?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.wasm')?'application/wasm':f.endsWith('.pdf')?'application/pdf':'application/octet-stream');res.end(fs.readFileSync(f));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});await page.setViewport({width:1440,height:1000});await page.setRequestInterception(true);page.on('request',r=>r.url().startsWith(origin)||/^(blob|data):/.test(r.url())?r.continue():r.respond({status:200,body:''}));
 await page.goto(origin+'/share');await page.click('#openShare');await page.waitForSelector('#cdqShareAppModal',{visible:true});await page.click('#cdqShareAppModal .cancel-button');assert.equal(await page.$('#cdqShareAppModal'),null);await page.click('#testAction');assert.equal(await page.evaluate(()=>clicks),1);
 await page.click('#openShare');await page.focus('#cdqShareNative');await page.keyboard.press('Escape');await page.click('#testAction');assert.equal(await page.evaluate(()=>clicks),2);assert.equal(page.url(),origin+'/share');
 assert.equal(await page.$eval('.pc16-nav button',e=>getComputedStyle(e).boxShadow),'none');assert.equal(await page.$eval('.pc16-nav button',e=>getComputedStyle(e,'::after').display),'none');
 for(const mobile of [false,true]){
  await page.setViewport(mobile?{width:393,height:850,isMobile:true,hasTouch:true}:{width:1440,height:1000});await page.goto(origin+'/host');await page.click('#open');await page.waitForSelector('#legacy-pdf-reader');const frame=await(await page.$('#legacy-pdf-reader')).contentFrame();await frame.waitForSelector('#viewer[data-ready="true"] input[name="client_nom"]');
  const before=await frame.$eval('input[name="charge_point_1_charge_contrainte"]',e=>e.value);assert.equal(before,'250');
  assert.equal(await frame.$eval('input[name="client_nom"]',e=>getComputedStyle(e).color),'rgb(0, 0, 0)');assert.equal(await frame.$eval('input[name="client_nom"]',e=>getComputedStyle(e).fontWeight),'700');
  await frame.click('#plus');await frame.click('#plus');await frame.click('#plus');await frame.waitForFunction(()=>parseInt(document.getElementById('zoom').textContent)>65);
  if(mobile){const cdp=await page.createCDPSession();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:210,y:650}]});for(let y=620;y>=300;y-=30){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:210,y}]});await new Promise(r=>setTimeout(r,16));}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await frame.waitForFunction(()=>document.getElementById('container').scrollTop>30);const scale=await frame.$eval('#zoom',e=>parseInt(e.textContent));for(const [type,points] of [['touchStart',[[110,300],[240,300]]],['touchMove',[[70,300],[290,300]]],['touchEnd',[]]])await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(([x,y],id)=>({x,y,id}))});await frame.waitForFunction(s=>parseInt(document.getElementById('zoom').textContent)>s,{},scale);assert.equal(await page.evaluate(()=>visualViewport.scale),1);}
  else{await frame.evaluate(()=>{document.getElementById('container').scrollTop=120});await page.mouse.move(700,400);await page.mouse.down();await page.mouse.move(480,250,{steps:12});await page.mouse.up();assert.ok(await frame.$eval('#container',e=>e.scrollLeft)>50);}
  assert.equal(await frame.$$eval('.canvasWrapper canvas',els=>els.filter(e=>getComputedStyle(e).display!=='none').length),1);
  await frame.$eval('input[name="client_nom"]',e=>e.scrollIntoView({block:'center'}));await frame.click('input[name="client_nom"]',{clickCount:3});await page.keyboard.type('Client QA modifie');await frame.click('#save');await page.waitForFunction(()=>window.saved instanceof Blob);assert.ok(await page.evaluate(()=>saved.size)>10000);
  await page.screenshot({path:'/tmp/cdq-v2525-reader-'+(mobile?'mobile':'pc')+'.png'});await frame.click('#back');await page.waitForSelector('#legacy-pdf-reader',{hidden:true});assert.equal(await browser.pages().then(p=>p.length),2);
 }
 assert.deepEqual(errors,[]);console.log('PASS V25.25: sharing close/Escape leaves app usable; PC underline gone; integrated single-canvas reader; PC pan, native mobile scroll, zoom, dark typing and confirmed save.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
