import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import puppeteer from 'puppeteer-core';import {fixture} from './helpers/desktop-ergonomics-fixture.mjs';
const read=p=>fs.readFileSync(p,'utf8'),dir='bundles/balance-cdq/v25.22',actual=process.env.CDQ_V2522_SELECTOR?read(process.env.CDQ_V2522_SELECTOR):'';
const styles=(actual?[...actual.matchAll(/<style\b[^>]*>[\s\S]*?<\/style>/gi)].map(x=>x[0]).join(''):'<style>'+read('bundles/balance-cdq/v25.18/desktop.css')+read('bundles/balance-cdq/v25.16/mobile-layout.css')+read('bundles/balance-cdq/v25.21/interface.css')+'</style>')+'<style>'+read(dir+'/interface.css')+'</style>';
const setup=`
window.cdqAccessState='ready';window.afficherMessage=(message)=>window.lastMessage=message;window.afficherErreur=e=>window.lastError=e.message||String(e);
window.held=[];window.holdOpen=false;window.holdCopy=false;window.copyError=false;window.opened=[];window.rpcCount=0;
const originalRpc=window.cdqApiRun;window.cdqApiRun=()=>{let ok=()=>{},fail=()=>{},obj,p;
 p=new Proxy({},{get:(_,name)=>name==='withSuccessHandler'?f=>{ok=f;return p}:name==='withFailureHandler'?f=>{fail=f;return p}:name==='withUserObject'?v=>{obj=v;return p}:(...args)=>{
 calls.push({name,args});rpcCount++;const run=()=>{try{let result;
 if(name==='obtenirContexteCopieCDQV2522')result={parentId:'current_folder123',parentName:'Archives',clientId:'c0'};
 else if(name==='obtenirDossiersClientsPCLeger')result=[{id:'other_client123',nom:'Autre client'}];
 else if(name==='obtenirDossiersCopieCDQV2522')result={crumbs:[{id:'master12345',nom:'Clients'},{id:'other_client123',nom:'Autre client'},...(args[0]==='nested_folder123'?[{id:args[0],nom:'Rapports'}]:[])],items:args[0]==='nested_folder123'?[]:[{id:'nested_folder123',nom:'Rapports'}]};
 else if(name==='copierElementCDQV2522'){if(copyError)throw Error('Drive indisponible');result={ok:true,id:'copied_report123',nom:'Balance - Copie.pdf',destinationId:args[1],clientId:'c0'};}
 else if(name==='ouvrirFichierPourModification'){opened.push(args[0]);result='https://example.test/file';}
 else result=window.rpcResult(name,args);
 ok(result,obj);}catch(e){fail(e,obj)}};
 if(holdOpen&&name==='ouvrirFichierPourModification'||holdCopy&&name==='copierElementCDQV2522')held.push(run);else setTimeout(run,20);
 }});return p;};
window.modifierFichier=id=>cdqApiRun().withSuccessHandler(()=>{}).withFailureHandler(afficherErreur).ouvrirFichierPourModification(id);
`;
const extras='<script>'+setup+'</script>'+['feedback','copy'].map(n=>'<script>'+read(dir+'/'+n+'.js')+'</script>').join('');
let pc=fixture().replace(read('bundles/balance-cdq/v25.18/desktop.js'),()=>read('bundles/balance-cdq/v25.21/extra-icons.js')+'\n'+read(dir+'/desktop.js'));
pc=pc.replace('<div class="pc16-side-meta">Balance CDQ<span></span></div>','<div class="pc16-side-meta">Balance CDQ<span></span></div><div class="pc16-side-user"><span class="avatar">JR</span><span class="copy"><b>JR Administrateur</b><small>● En ligne</small></span></div>');
pc=pc.replace('</head>',()=>styles+'</head>').replace('</body>',()=>extras+'</body>');
const phoneSetup=`window.utilisateurCourantEmail='demo@example.test';window.utilisateurCourantRole='admin';window.calls=[];window.modeSelectionFichiers=false;window.dossiersSelectionnes=new Set();window.isWindows=()=>false;window.cdqIsOwner=()=>true;window.cdqToggleFolderProtection=()=>{};window.cdqToggleFolderFavorite=()=>{};window.cdqToggleFileFavorite=()=>{};window.ouvrirNoteFichier=()=>{};window.ouvrirPhotosCible=()=>{};window.renommerFichier=()=>{};window.ouvrirConfirmationSuppression=()=>{};window.ouvrirConfirmation=()=>{};window.cdqSelectOnly=()=>{};window.mettreAJourInterface=()=>{};window.obtenirDureeAppuiLongSelection=()=>700;window.obtenirSeuilGlissement=()=>55;window.obtenirRatioGlissement=()=>1.5;`;
const phone='<!doctype html><html class="android cdq-mobile-layout"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'+styles+'<style>body{margin:0;padding:12px;background:#070a0f;color:white}.file-row,.folder-header{position:relative;min-height:62px;border:1px solid #666;margin:12px 0}.cdq-swipe-overlay{display:none;position:absolute;inset:0;align-items:center}.cdq-swiped-right .cdq-swipe-overlay.right{display:flex}.cdq-swipe-action{min-height:42px}</style></head><body><header id="appHeader"></header><div id="selectionBar" class="selection-bar selection-mode-bar" style="display:flex"><div class="selection-mode-copy"><strong>Mode sélection</strong><span>Maintiens un fichier ou un dossier 1 seconde pour commencer</span></div><span id="fileCount">1 fichier sélectionné</span><button id="deleteButton">🗑</button><button id="finishSelectionButton">×</button></div><div class="file-row" id="testFile">Balance.pdf</div><div class="folder-header" id="testFolder">Archives</div><script>'+phoneSetup+'</script>'+extras+'<script>'+read('tests/fixtures/legacy-phone-swipes.js')+'\n'+read('tests/fixtures/copy-swipes-v2522.js')+'\ncdqEnhanceFileSwipe(testFile,{id:"file_report12345",nom:"Balance.pdf"});cdqEnhanceFolderSwipe(testFolder,{id:"folder_archive123",nom:"Archives"},false);</script></body></html>';
let latest='V25.23';const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(req.url==='/phone'?phone:pc)});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.setRequestInterception(true);page.on('request',r=>{if(r.url().startsWith('http://127.0.0.1:')||r.url().startsWith('data:'))return r.continue();if(r.url().includes('/latest/manifest.json'))return r.respond({status:200,contentType:'application/json',headers:{'Access-Control-Allow-Origin':'*'},body:JSON.stringify({version:latest,build:'2026.09.24-'+latest.toLowerCase()+'-test'})});r.respond({status:200,body:''})});
const url='http://127.0.0.1:'+server.address().port,wait=ms=>new Promise(r=>setTimeout(r,ms));
async function drag(selector){const box=await page.$eval(selector,e=>{const b=e.getBoundingClientRect();return {x:b.x+15,y:b.y+b.height/2}});await page.mouse.move(box.x,box.y);await page.mouse.down();await page.mouse.move(box.x+115,box.y+2,{steps:8});await page.mouse.up();}
try{
 await page.setViewport({width:1440,height:900});await page.goto(url);await page.click('#demoLogin');await page.waitForSelector('.pc22-version');
 assert.equal(await page.$('.pc17-clock'),null);assert.equal(await page.$('.pc16-side-meta'),null);assert.equal(await page.$eval('.pc22-version',e=>e.textContent),'V25.22');
 const profile=await page.evaluate(()=>{const a=document.querySelector('.pc22-network').getBoundingClientRect(),b=document.querySelector('.pc22-version').getBoundingClientRect();return Math.abs(a.y-b.y)});assert.ok(profile<2);
 await page.waitForFunction(()=>document.querySelector('#cdqUpdateV2522')&&!document.querySelector('#cdqUpdateV2522').hidden);assert.match(await page.$eval('#cdqUpdateV2522',e=>e.textContent),/25.23/);
 latest='V25.22';await page.evaluate(()=>cdqFeedbackV2522.check(true));await page.waitForFunction(()=>document.querySelector('#cdqUpdateV2522').hidden);
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{origin:'https://evil.invalid',source:window,data:{type:'CDQ_UPDATE_STATUS',available:true,latest:'V99.99'}})));assert.equal(await page.$eval('#cdqUpdateV2522',e=>e.hidden),true);
 await page.evaluate(()=>holdOpen=true);await page.click('[data-file="f0"] b',{clickCount:2});await page.waitForFunction(()=>!document.querySelector('#cdqBusyV2522').hidden);assert.equal(await page.$eval('#cdqPcV16',e=>e.getAttribute('aria-busy')),'true');await page.evaluate(()=>held.shift()());await page.waitForFunction(()=>document.querySelector('#cdqBusyV2522').hidden);
 await page.click('[data-view="clients"]');await page.click('[data-client="c0"] .pc17-open-client');await page.waitForSelector('[data-file="archive"]');await drag('[data-file="archive"]');await page.click('[data-file="archive"] [data-copy]');await page.waitForFunction(()=>!document.querySelector('.copy-confirm').disabled);assert.match(await page.$eval('.copy-destination',e=>e.textContent),/Archives/);
 await page.click('.copy-options button:nth-child(2)');await page.waitForSelector('.copy-list button');await page.click('.copy-list button');await page.waitForFunction(()=>document.querySelector('.copy-list button')?.textContent.includes('Rapports'));await page.click('.copy-list button');await page.waitForFunction(()=>document.querySelector('.copy-destination').textContent.includes('Rapports'));
 await page.evaluate(()=>holdCopy=true);await page.click('.copy-confirm');assert.equal(await page.$eval('.copy-confirm',e=>e.disabled),true);assert.equal(await page.$$eval('#cdqCopyV2522 footer button',es=>es.every(e=>e.disabled)),true);await page.evaluate(()=>held.shift()());await page.waitForFunction(()=>!document.querySelector('#cdqCopyV2522').open);
 assert.deepEqual(await page.evaluate(()=>calls.filter(c=>c.name==='copierElementCDQV2522').at(-1).args.slice(0,2)),['archive','nested_folder123']);
 latest='V25.23';await page.evaluate(()=>cdqFeedbackV2522.check(true));await page.screenshot({path:'/tmp/cdq-v2522-pc.png'});
 for(const width of [393,320]){
  await page.setViewport({width,height:851,isMobile:true,hasTouch:true});await page.goto(url+'/phone');
  const size=await page.evaluate(()=>({height:selectionBar.getBoundingClientRect().height,overflow:document.documentElement.scrollWidth>innerWidth,count:getComputedStyle(fileCount).fontSize}));assert.ok(size.height<=58,JSON.stringify(size));assert.equal(size.overflow,false);assert.equal(size.count,'14px');
  for(const row of ['#testFile','#testFolder']){
   await drag(row);await page.waitForFunction(s=>document.querySelector(s).classList.contains('cdq-swiped-right'),{},row);assert.ok(await page.$eval(row+' .copy',e=>e.getBoundingClientRect().width>35));
   await page.click(row+' .copy');await page.waitForFunction(()=>!document.querySelector('.copy-confirm').disabled);await page.screenshot({path:'/tmp/cdq-v2522-copy-'+width+'.png'});await page.click('#cdqCopyV2522 footer button');
  }
  await page.screenshot({path:'/tmp/cdq-v2522-phone-'+width+'.png'});
  await page.evaluate(()=>{cdqCopyV2522.open({id:'file_report12345',nom:'Balance.pdf'});});await page.waitForFunction(()=>!document.querySelector('.copy-confirm').disabled);await page.evaluate(()=>copyError=true);await page.click('.copy-confirm');await page.waitForFunction(()=>document.querySelector('.copy-status').classList.contains('error'));assert.equal(await page.$eval('.copy-confirm',e=>e.disabled),false);assert.equal(await page.evaluate(()=>window.lastMessage||''),'');
 }
 assert.deepEqual(errors,[]);console.log('PASS: compact 393/320px selection, PC profile, loading lifecycle, update detection, file/folder swipe and destination copy, error recovery.');
}catch(e){await page.screenshot({path:'/tmp/cdq-v2522-failure.png'});console.error({errors});throw e}finally{await browser.close();server.close()}
