import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import test from 'node:test';import assert from 'node:assert/strict';import {applyPatch} from './helpers/settings-fixture.mjs';
const dir='bundles/balance-cdq/v25.21',read=p=>fs.readFileSync(p,'utf8'),manifest=JSON.parse(read(dir+'/manifest.json'));
test('Package supports V25.19 and V25.20 and uses current modules and checked server bytes',()=>{
 assert.deepEqual(manifest,JSON.parse(read(dir+'/Balance_CDQ_V25_21.cdq')));assert.deepEqual(manifest.requiresBuild,['2026.09.23-v25.19-plancher-integre','2026.09.23-v25.20-lecteurs-pdf']);
 for(const f of ['floor-bridge.js','desktop.js','admin-functions.js','extra-icons.js','drive-browser.js']){const source=read(dir+'/'+f);new vm.Script(source);assert.ok(manifest.patches.some(p=>p.replacement?.includes(source)),f)}
 const extra=manifest.extraFiles[0];assert.equal(crypto.createHash('sha256').update(read(dir+'/files/'+extra.name)).digest('hex'),extra.sha256);
 if(process.env.CDQ_V2520_SOURCE)for(const file of ['Selector.html','Code.gs']){let source=read(process.env.CDQ_V2520_SOURCE+'-'+file);for(const p of manifest.patches.filter(p=>p.file===file))source=applyPatch(source,p);fs.writeFileSync('/tmp/cdq-v2521-'+file,source);if(file==='Code.gs')new vm.Script(source);else for(const block of source.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi))if(!block[1].includes('application/json'))new vm.Script(block[2]);}
});
const ROOT='1F7rgU20Hc1PmjxQHY7ALTqkqArN6RSsf',MASTER='master_1234567890',FOLDER='folder_1234567890',FILE='report_1234567890',OUTSIDE='outside_123456789',SHORTCUT='shortcut_123456789',F='application/vnd.google-apps.folder';
function fixture(){const props=new Map(),calls=[],meta={
 [ROOT]:{id:ROOT,name:'Général',mimeType:F},[MASTER]:{id:MASTER,name:'Clients',mimeType:F},
 [FOLDER]:{id:FOLDER,name:'Dossier jaune',mimeType:F,parents:[ROOT]},[FILE]:{id:FILE,name:'Rapport.pdf',mimeType:'application/pdf',parents:[MASTER],starred:true},
 [OUTSIDE]:{id:OUTSIDE,name:'Autre',mimeType:F},[SHORTCUT]:{id:SHORTCUT,name:'Lien',mimeType:'application/vnd.google-apps.shortcut',parents:[ROOT]}
 };let email='a@example.invalid',allowed=true,locked=false;const c=vm.createContext({console,CONFIG:{MASTER_FOLDER_ID:MASTER},verifierDroit_:role=>{calls.push('auth');assert.equal(role,'lecture');if(!allowed)throw Error('Non autorisé');return {email,role:'lecture'}},empreinteCDQ_:s=>crypto.createHash('sha256').update(s).digest('hex'),PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k),setProperty:(k,v)=>props.set(k,v)})},LockService:{getScriptLock:()=>({waitLock:()=>{locked=true},releaseLock:()=>{locked=false}})},Drive:{Files:{get:(id,options)=>{calls.push({get:id});if(!meta[id])throw Error('introuvable');assert.equal(options.supportsAllDrives,true);return structuredClone(meta[id])},list:options=>{calls.push(options);return {files:options.q.includes('starred=true')?(options.pageToken?[meta[OUTSIDE]]:[meta[FILE]]):[meta[FOLDER]],nextPageToken:options.pageToken?'':'nextpage'}}}}});vm.runInContext(read(dir+'/files/CDQDriveBrowser.gs'),c);return {c,meta,props,calls,setEmail:x=>email=x,setAllowed:x=>allowed=x,locked:()=>locked};}
test('Drive auth precedes reads; only requested root and client root can be traversed',()=>{const f=fixture();f.setAllowed(false);assert.throws(()=>f.c.obtenirDossierGeneralCDQV2521(),/autorisé/);assert.deepEqual(f.calls,['auth']);f.setAllowed(true);assert.equal(f.c.obtenirDossierGeneralCDQV2521().id,ROOT);assert.equal(f.c.obtenirDossierGeneralCDQV2521(MASTER).id,MASTER);assert.equal(f.c.obtenirDossierGeneralCDQV2521(FOLDER).crumbs[0].id,ROOT);assert.throws(()=>f.c.obtenirDossierGeneralCDQV2521(OUTSIDE),/autorisés/);assert.throws(()=>f.c.definirFavoriGeneralCDQV2521(SHORTCUT,true),/raccourci/);f.meta[FOLDER].trashed=true;assert.throws(()=>f.c.definirFavoriGeneralCDQV2521(FOLDER,true),/supprimé/);assert.throws(()=>f.c.obtenirDossierGeneralCDQV2521("x' or trashed=false"),/invalide/);});
test('Favorites are per account; removal of legacy stars does not modify Drive or other users',()=>{const f=fixture();assert.equal(f.c.definirFavoriGeneralCDQV2521(FOLDER,true).favori,true);assert.equal(f.c.obtenirFavorisGenerauxCDQV2521().items.length,2);f.c.definirFavoriGeneralCDQV2521(FILE,false);assert.deepEqual(Array.from(f.c.obtenirFavorisGenerauxCDQV2521().items,x=>x.id),[FOLDER]);assert.equal(f.meta[FILE].starred,true);f.setEmail('b@example.invalid');assert.deepEqual(Array.from(f.c.obtenirFavorisGenerauxCDQV2521().items,x=>x.id),[FILE]);assert.equal(f.c.obtenirDossierGeneralCDQV2521().items[0].favori,false);f.setEmail('a@example.invalid');assert.equal(f.c.obtenirDossierGeneralCDQV2521().items[0].favori,true);assert.equal(f.locked(),false)});
test('Pagination forwards tokens and revalidates starred results; moved favorites disappear',()=>{const f=fixture();f.c.definirFavoriGeneralCDQV2521(FOLDER,true);assert.equal(f.c.obtenirDossierGeneralCDQV2521(ROOT).nextPageToken,'nextpage');f.c.obtenirDossierGeneralCDQV2521(ROOT,'nextpage');assert.equal(f.calls.at(-1).pageToken,'nextpage');assert.equal(f.c.obtenirFavorisGenerauxCDQV2521('nextpage').items.length,0);f.meta[FOLDER].parents=[OUTSIDE];assert.deepEqual(Array.from(f.c.obtenirFavorisGenerauxCDQV2521().items,x=>x.id),[FILE]);assert.throws(()=>f.c.obtenirFavorisGenerauxCDQV2521('\0'),/invalide/)});
test('Native black screen changes preserve the existing paused APK publication guard',()=>{assert.match(read('balance-cdq-android/app/src/main/res/values/ic_launcher_colors.xml'),/#000000/);assert.match(read('balance-cdq-android/app/src/main/java/ca/balancecdq/android/MainActivity.kt'),/setBackgroundColor\(Color.BLACK\)/);assert.match(read('.github/workflows/build-balance-cdq-android.yml'),/signing|signature/i);});
