import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const read=p=>fs.readFileSync(p,'utf8'),json=p=>JSON.parse(read(p));
const native='balance-cdq-android/app/build/generated/cdq-web-assets/cdq-web/';
const android=json(native+'asset-manifest.json'),iphone=json('iphone/app/release.json');
assert.equal(iphone.version,android.version);
assert.equal(iphone.androidSourceBuild,android.build);
assert.equal(iphone.androidSelectorSha256,android.files['Selector.html'].sha256);
for(const name of ['assets/templates/balance-plancher-v2519.pdf','assets/music-wall-android-v2523.webp','icons/icon-heavy-v3-192.png'])assert.deepEqual(fs.readFileSync(native+name),fs.readFileSync('iphone/app/'+name),name+' must not change');
const shell=read('iphone/app/index.html'),selector=read('iphone/app/Selector.html'),sw=read('iphone/app/sw.js'),update=read('iphone/app/iphone-update.js');
assert.match(shell,/accounts\.google\.com\/gsi\/client/);
assert.match(shell,/apple-mobile-web-app-capable/);
assert.match(selector,/cdq-instant-files-2530/);
assert(!selector.includes('<script id="cdqV2503UpdateHandoffJs">'));
assert(!selector.includes('<script id="cdqV2313AndroidUpdaterJs">'));
assert(!shell.includes('/native/v'+android.version+'/'));
assert(!selector.includes('/native/v'+android.version+'/'));
const manifest=json('iphone/app/manifest.webmanifest');
assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./');assert.equal(manifest.display,'standalone');
assert.match(update,/Enregistrez et fermez vos documents/);
assert.match(update,/event|e\.origin!==origin/);
assert.match(sw,/event\.data\.release===RELEASE/);
assert(!sw.includes("url.hostname==='drive.google.com'"));
const assets=JSON.parse(sw.match(/ASSETS=(\{.*\});/)[1]);
assert(!assets['release.json']);assert(!assets['sw.js']);
for(const [name,hash] of Object.entries(assets))assert.equal(crypto.createHash('sha256').update(fs.readFileSync('iphone/app/'+name)).digest('hex'),hash,'Cache checksum '+name);
const install=read('installer.html');
assert.match(install,/Application Android/);assert.match(install,/Application iPhone/);
assert.match(install,/data-copy="android"/);assert.match(install,/data-copy="iphone"/);
assert.match(install,/e?rror\?\.name==='AbortError'/);
if(process.env.CDQ_ALLOW_UNPUBLISHED_ANDROID!=='1')assert(fs.existsSync('downloads/Balance-CDQ-Android-'+android.version+'.apk'),'Do not advertise an unpublished APK');
const apple=read('iphone/index.html');assert.match(apple,/<base href="\.\.\/">/);assert.match(apple,/manifest\.webmanifest/);
console.log('PASS: shared Android source, unchanged artwork/PDF, iPhone manifest, isolated updater, all '+Object.keys(assets).length+' cache checksums and two valid install channels.');
