import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const root='bundles/balance-cdq/v25.23/files/',code=fs.readFileSync(root+'CDQFloorMapping.gs','utf8'),migration=fs.readFileSync(root+'CDQFloorMigration.gs','utf8');
function sample(){const rows=Array.from({length:75},()=>Array(100).fill(''));const set=(r,c,v)=>rows[r-1][c-1]=v;for(const [r,c,v] of [[14,4,'Client :'],[14,5,'Client test'],[14,40,'Ville :'],[14,41,'Ville test'],[23,1,'Type :'],[23,5,'Balance de plancher'],[29,47,'2268Kg x 0.5Kg'],[35,19,'TRUE'],[37,82,'Charge:'],[37,89,'200'],[48,1,'Étendue de la balance utilisée :'],[48,19,'200 kg'],[50,6,'Poids'],[50,25,'Charge utilisée'],[50,44,'Avant correction'],[50,63,'Tolérance'],[50,82,'Après correction'],[51,6,'200'],[51,25,'9999'],[51,44,'201'],[51,63,'9999'],[51,82,'200'],[57,67,"Poids étalons utilisés pour l'étalonnage :"],[57,68,'Kit test'],[69,10,'Technicien test'],[69,47,"Date d'étalonnage :"],[69,58,'25'],[69,61,'8'],[69,64,'26'],[69,79,'Date due :'],[69,88,'8'],[69,91,'27']])set(r,c,v);for(let i=0;i<4;i++){set(43,57+11*i,String(i+1));set(44,57+11*i,String(200+i*.5));set(45,57+11*i,'200');}return rows;}
function parser(){const c=vm.createContext({});vm.runInContext(code,c);return c.cdq23ParseSheet_;}
test('Sheet mapping imports raw Poids, keeps missing dates empty and maps corners by the diagram',()=>{const r=parser()(sample());assert.equal(r.skip,false);assert.equal(r.values.charge_point_1_charge_utilisee,'200');assert.equal(r.values.charge_point_1_avant_correction,'201');assert.equal(r.values.charge_point_1_apres_correction,'200');assert.equal(r.values.charge_point_1_tolerance,undefined);assert.equal(r.values.charge_point_1_charge_contrainte,undefined);assert.equal(r.values.frequence_etalonnage,'12 mois');assert.equal(r.values.prochain_etalonnage_1,undefined);assert.equal(r.values.excentricite_avant_avant_gauche,'200');assert.equal(r.values.excentricite_avant_arriere_gauche,'200.5');assert.equal(r.values.excentricite_avant_arriere_droit,'201');assert.equal(r.values.excentricite_avant_avant_droit,'201.5');assert.equal(r.values.echelon,'0.5');assert.equal(r.values.etalon_utilise,'Kit test');assert.equal(r.values.etendue_verifiee,'200 kg');});
test('Filename cannot override Type; ambiguous units and shifted headers cannot silently produce a report',()=>{const parse=parser(),rows=sample();rows[22][4]='Balance de table';assert.equal(parse(rows).skip,true);rows[22][4]='Balance de plancher';rows[34][14]='TRUE';assert.throws(()=>parse(rows),/Unité/);rows[34][14]='FALSE';rows[49][43]='Autre';assert.throws(()=>parse(rows),/Colonnes/);});
test('Zero readings survive while dash placeholders are empty and comma decimals are accepted',()=>{const rows=sample();rows[50][43]='0';rows[50][81]='--';rows[51][5]='0,5';const v=parser()(rows).values;assert.equal(v.charge_point_1_avant_correction,'0');assert.equal(v.charge_point_1_apres_correction,undefined);assert.equal(v.charge_point_2_charge_utilisee,'0.5');});
function harness(){let owner=true,saveFail=false,revision='r1',creates=0,reserved=0;const out={},s={id:'job-uuid',status:'running',phase:'convert',queue:[{id:'sheet_abcdefgh',name:'Balance QA',clientId:'client_abcdefgh',clientName:'Client test',path:'',status:'pending'}]};let durable=JSON.stringify(s);const dest='1XWvvenKIbZxqWUAhDyVQIM0gIPzzJ1IP';
 const c=vm.createContext({Date,JSON,CONFIG:{MASTER_FOLDER_ID:'root_original'},verifierProprietairePrincipal_:()=>{if(!owner)throw Error('ACTION RÉSERVÉE');return {email:'owner@example.invalid'};},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Utilities:{getUuid:()=>crypto.randomUUID(),base64Decode:x=>Buffer.from(x,'base64'),newBlob:x=>x},Drive:{Files:{generateIds:()=>({ids:['reserved_'+(++reserved)]}),get:id=>{if(!out[id])throw Error('404 not found');return out[id];},create:(m)=>{creates++;out[m.id]={...m,trashed:false};return {id:m.id};}}},cdqDriveScopeV2521_:(id)=>id==='reports_test'?{meta:{mimeType:'application/vnd.google-apps.folder'},path:[{id:dest},{id:'dest_client',nom:'Client test'},{id:'reports_test'}]}:{meta:{modifiedTime:revision},path:[{id:'root_original'},{id:'client_abcdefgh'},{id}]}});
 vm.runInContext(code+'\n'+migration,c);c.cdq23ReadJob_=()=>({file:{},state:JSON.parse(durable)});c.cdq23WriteJob_=j=>{if(saveFail){saveFail=false;throw Error('response lost');}durable=JSON.stringify(j.state);};c.cdq23ReadSource_=()=>({data:parser()(sample()),revision});c.cdq23Folder_=()=> 'dest_client';c.cdq23Reports_=()=> 'reports_test';c.cdq23List_=()=>({files:[]});
 return {c,get state(){return JSON.parse(durable)},get creates(){return creates},get reserved(){return reserved},setOwner(v){owner=v},failCheckpoint(){saveFail=true},changeSource(){revision='r2'},pdf:Buffer.from('%PDF-'+'.'.repeat(11000)).toString('base64')};
}
test('Owner check applies to every entrypoint; a lease blocks a competing tab',()=>{const h=harness();h.setOwner(false);for(const f of ['obtenirConversionPlancherCDQV2523','demarrerConversionPlancherCDQV2523','suspendreConversionPlancherCDQV2523'])assert.throws(()=>h.c[f](),/RÉSERVÉE/);h.setOwner(true);const first=h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123');assert.ok(first.work);const second=h.c.prochaineConversionPlancherCDQV2523('session-two-1234567890123');assert.equal(second.wait,true);assert.equal(h.reserved,1);assert.equal(h.creates,0);});
test('Lost checkpoint after upload resumes using reserved PDF ID without a duplicate',()=>{const h=harness(),step=h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123');h.failCheckpoint();assert.throws(()=>h.c.enregistrerConversionPlancherCDQV2523(step.work.id,step.work.token,h.pdf),/response lost/);assert.equal(h.creates,1);const resumed=h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123');assert.equal(resumed.progress.converted,1);assert.equal(h.creates,1);assert.equal(h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123').progress.status,'completed');});
test('Pause allows only the reserved file to finish; a changed source is never uploaded',()=>{let h=harness(),step=h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123');h.c.suspendreConversionPlancherCDQV2523();assert.equal(h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123').work,undefined);assert.equal(h.c.enregistrerConversionPlancherCDQV2523(step.work.id,step.work.token,h.pdf).converted,1);h=harness();step=h.c.prochaineConversionPlancherCDQV2523('session-one-1234567890123');h.changeSource();assert.throws(()=>h.c.enregistrerConversionPlancherCDQV2523(step.work.id,step.work.token,h.pdf),/changé/);assert.equal(h.creates,0);});
