import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import puppeteer from 'puppeteer-core';
const server=http.createServer((req,res)=>{let path=new URL(req.url,'http://localhost').pathname.slice(1);if(path==='host'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><html><body>Test PDF</body></html>');}if(path.includes('..')||!fs.existsSync(path)||!fs.statSync(path).isFile()){res.statusCode=404;return res.end();}res.setHeader('Content-Type',path.endsWith('.mjs')||path.endsWith('.js')?'text/javascript':path.endsWith('.wasm')?'application/wasm':path.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(path));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await puppeteer.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/google-chrome',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
try{const page=await browser.newPage();page.on('console',m=>{if(['error','log'].includes(m.type()))console.log('Browser:',m.text());});await page.goto('http://127.0.0.1:'+server.address().port+'/host');
 const values={client_nom:'Client fictif — QA',client_ville:'Ville test',client_technicien:'Technicien historique test',etalon_utilise:'Kit historique test',unite_mesure:'kg',capacite_maximale:'2268',echelon:'0.5',date_etalonnage_1:'25',date_etalonnage_2:'8',date_etalonnage_3:'2026',frequence_etalonnage:'12 mois',prochain_etalonnage_2:'8',prochain_etalonnage_3:'2027',charge_point_1_charge_utilisee:'200',charge_point_1_avant_correction:'201',charge_point_1_apres_correction:'200',charge_excentricite:'200',excentricite_avant_avant_gauche:'200.5',excentricite_avant_arriere_gauche:'201',excentricite_avant_arriere_droit:'200.5',excentricite_avant_avant_droit:'201',excentricite_apres_avant_gauche:'200',excentricite_apres_arriere_gauche:'200',excentricite_apres_arriere_droit:'200',excentricite_apres_avant_droit:'200'};
 const result=await page.evaluate(async values=>{const {fillInFrame}=await import('/pdf-fill-client-v2523.mjs');const blob=await fillInFrame(values);const api=await import('/vendor/pdfjs-6.3.289/build/pdf.mjs');api.GlobalWorkerOptions.workerSrc='/vendor/pdfjs-6.3.289/build/pdf.worker.mjs';const doc=await api.getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false}).promise,objects=await doc.getFieldObjects(),fields=Object.fromEntries([...objects].map(([k,v])=>[k,v[0].value]));let binary='';const bytes=new Uint8Array(await blob.arrayBuffer());for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return {fields,actions:!!await doc.getJSActions(),base64:btoa(binary)};},values);
 fs.writeFileSync('/tmp/cdq-v2523-filled.pdf',Buffer.from(result.base64,'base64'));
 for(const [k,v] of Object.entries(values))assert.equal(String(result.fields[k]),v,k);
 console.log('Calculated values:',JSON.stringify(Object.fromEntries(Object.entries(result.fields).filter(([k])=>/charge_point_1|tolerance_excentricite|prochain_etalonnage/.test(k)))));
 assert.equal(String(result.fields.charge_point_1_erreur_avant),'2');assert.equal(String(result.fields.charge_point_1_erreur_apres),'0');assert.ok(result.fields.charge_point_1_tolerance);assert.equal(result.fields.prochain_etalonnage_1,'');assert.ok(result.actions);
 await assert.rejects(page.evaluate(async()=>{const {fillInFrame}=await import('/pdf-fill-client-v2523.mjs');await fillInFrame({charge_point_1_tolerance:'999'});}),/Champ de transfert refusé/);
 console.log('PASS: saved/reopened PDF preserves raw inputs, original calculations, partial date, scripts and historical choices.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
