import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
const source=fs.readFileSync('bundles/balance-cdq/v25.20/files/CDQPdfReader.gs','utf8');
function fixture(){
  let allowed=true,client=true,writes=0;const initial='%PDF-1.7 original',replacement='%PDF-1.7 filled';
  const state={id:'PDF_CLIENT_123456',name:'Balance de plancher.pdf',mimeType:'application/pdf',trashed:false,modifiedTime:'2026-09-23T00:00:00.000Z',appProperties:{existing:'preserved'},bytes:Buffer.from(initial)};
  const c=vm.createContext({Buffer,Date,CDQ_DOCUMENT_MAX_BYTES_:32*1024*1024,CDQ_DOCUMENT_CHUNK_BYTES_:4*1024*1024,
    verifierDroit_:()=>{if(!allowed)throw Error('Denied');return {email:'tech@example.invalid'}},verifierCibleDansMasterCDQ_:()=>{if(!client)throw Error('Not a client PDF')},
    obtenirPdfClientCDQ_:()=>({client:{getId:()=> 'CLIENT_123456'},fichier:{getId:()=>state.id,getSize:()=>state.bytes.length,getName:()=>state.name,getLastUpdated:()=>new Date(state.modifiedTime),getBlob:()=>({getBytes:()=>[...state.bytes]})}}),
    empreinteCDQ_:s=>crypto.createHash('sha256').update(s).digest('hex'),invaliderCacheContenuClient_:()=>{},invaliderCacheCompagnies_:()=>{},
    Utilities:{base64Decode:s=>[...Buffer.from(s,'base64')],base64Encode:b=>Buffer.from(b).toString('base64'),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,b)=>[...crypto.createHash('sha256').update(Buffer.from(b)).digest()],newBlob:b=>Buffer.from(b)},
    LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Drive:{Files:{get:()=>({...state,appProperties:{...state.appProperties}}),update:(meta,id,bytes)=>{assert.equal(id,state.id);writes++;state.bytes=bytes;state.appProperties={...state.appProperties,...meta.appProperties};state.modifiedTime='2026-09-23T00:01:00.000Z';return {...state};}}}});
  vm.runInContext(source,c);return {c,state,replacement,get writes(){return writes},deny:()=>{allowed=false},outside:()=>{client=false}};
}
test('Small PDF opens in one RPC; unchanged revision returns metadata without bytes',()=>{const f=fixture();assert.equal(f.c.obtenirPdfLecteurCDQV2520(f.state.id,'').base64,Buffer.from('%PDF-1.7 original').toString('base64'));const r=f.c.obtenirPdfLecteurCDQV2520(f.state.id,f.state.modifiedTime);assert.equal(r.unchanged,true);assert.equal(r.base64,undefined);});
test('Save updates the same file and preserves its name, folder and unrelated properties',()=>{const f=fixture();const r=f.c.enregistrerPdfLecteurCDQV2520(f.state.id,Buffer.from(f.replacement).toString('base64'),'save-1234567890',f.state.modifiedTime);assert.equal(r.id,f.state.id);assert.equal(f.writes,1);assert.equal(f.state.bytes.toString(),f.replacement);assert.equal(f.state.appProperties.existing,'preserved');});
test('A lost response can be retried without another update; changed retry content rejected',()=>{const f=fixture(),rev=f.state.modifiedTime,b64=Buffer.from(f.replacement).toString('base64');f.c.enregistrerPdfLecteurCDQV2520(f.state.id,b64,'save-1234567890',rev);f.c.enregistrerPdfLecteurCDQV2520(f.state.id,b64,'save-1234567890',rev);assert.equal(f.writes,1);assert.throws(()=>f.c.enregistrerPdfLecteurCDQV2520(f.state.id,Buffer.from('%PDF-other').toString('base64'),'save-1234567890',rev),/autre contenu/);});
test('A changed or missing revision never overwrites the client PDF',()=>{for(const rev of ['','2026-09-22T00:00:00Z']){const f=fixture();assert.throws(()=>f.c.enregistrerPdfLecteurCDQV2520(f.state.id,Buffer.from(f.replacement).toString('base64'),'save-1234567890',rev),/modifié depuis/);assert.equal(f.writes,0);}});
test('Read-only access, system templates, invalid data and trashed targets cannot be written',()=>{for(const setup of [f=>f.deny(),f=>f.outside(),f=>f.state.trashed=true,f=>f.state.mimeType='text/plain']){const f=fixture();setup(f);assert.throws(()=>f.c.enregistrerPdfLecteurCDQV2520(f.state.id,Buffer.from(f.replacement).toString('base64'),'save-1234567890',f.state.modifiedTime));assert.equal(f.writes,0);}const f=fixture();assert.throws(()=>f.c.enregistrerPdfLecteurCDQV2520(f.state.id,Buffer.from('not a pdf').toString('base64'),'save-1234567890',f.state.modifiedTime));assert.equal(f.writes,0);});
