const CDQ={token:'',content:null,version:null};const SCOPES='https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/script.deployments';
function scriptId(){const v=document.getElementById('scriptId').value.trim();const m=v.match(/\/projects\/([A-Za-z0-9_-]+)/);return m?m[1]:v.replace(/\s+/g,'')}
async function googleReady(){for(let i=0;i<50;i++){if(window.google?.accounts?.oauth2)return;await new Promise(r=>setTimeout(r,100))}throw Error('Connexion Google non chargée.')}
async function auth(){if(CDQ.token)return;await googleReady();const id=document.getElementById('clientId').value.trim();if(!id)throw Error('OAuth Client ID manquant.');await new Promise((ok,no)=>{const c=google.accounts.oauth2.initTokenClient({client_id:id,scope:SCOPES,callback:r=>{if(r.error)return no(Error(r.error_description||r.error));CDQ.token=r.access_token;ok()}});c.requestAccessToken({prompt:'consent'})})}
async function gapi(path,opt={}){await auth();const r=await fetch('https://script.googleapis.com/v1'+path,{...opt,headers:{Authorization:'Bearer '+CDQ.token,'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={raw:t}}if(!r.ok){if(r.status===401)CDQ.token='';throw Error(d?.error?.message||d.raw||('Erreur Google '+r.status))}return d}
async function getContent(){const id=scriptId();if(!id)throw Error('Script ID manquant.');CDQ.content=await gapi('/projects/'+encodeURIComponent(id)+'/content');return CDQ.content}
async function getDeployments(){return gapi('/projects/'+encodeURIComponent(scriptId())+'/deployments')}
function base(n,t){n=n.trim();return t==='SERVER_JS'?n.replace(/\.gs$/i,''):n.replace(/\.html?$/i,'')}
function replaceFile(files,name,type,source){const n=base(name,type);let f=files.find(x=>x.type===type&&x.name.toLowerCase()===n.toLowerCase());if(f)f.source=source;else files.push({name:n,type,source})}
async function updateFiles(code,selector){const cur=await getContent();saveBackup(cur);if(!cur.files?.some(f=>f.type==='JSON'&&f.name==='appsscript'))throw Error('appsscript.json introuvable.');const files=JSON.parse(JSON.stringify(cur.files));if(code)replaceFile(files,codeName.value,'SERVER_JS',codeEditor.value);if(selector)replaceFile(files,selectorName.value,'HTML',selectorEditor.value);CDQ.content=await gapi('/projects/'+encodeURIComponent(scriptId())+'/content',{method:'PUT',body:JSON.stringify({files})});return CDQ.content}
async function createVersion(){CDQ.version=await gapi('/projects/'+encodeURIComponent(scriptId())+'/versions',{method:'POST',body:JSON.stringify({description:description.value.trim()||'Mise à jour CDQ'})});return CDQ.version}
async function deployVersion(v){const dep=deployment.value;if(!dep)throw Error('Choisis le déploiement existant.');return gapi('/projects/'+encodeURIComponent(scriptId())+'/deployments/'+encodeURIComponent(dep),{method:'PUT',body:JSON.stringify({deploymentConfig:{scriptId:scriptId(),versionNumber:v.versionNumber,manifestFileName:'appsscript',description:description.value.trim()||'Mise à jour CDQ'}})})}