const $=id=>document.getElementById(id),LS=localStorage;let installPrompt=null;function msg(t,k=''){status.textContent=t;status.className=k}function setTopStatus(t,k=''){topStatus.textContent=t;topStatus.className=k}function saveBackup(c){LS.setItem('cdq_backup',JSON.stringify({date:new Date().toISOString(),scriptId:scriptId(),content:c}));backupInfo.textContent='Sauvegarde : '+new Date().toLocaleString('fr-CA',{hour12:false})}function readBackup(){try{return JSON.parse(LS.getItem('cdq_backup')||'null')}catch{return null}}
function saveSettings(){LS.setItem('cdq_client',clientId.value);LS.setItem('cdq_script',scriptId());LS.setItem('cdq_code_name',codeName.value);LS.setItem('cdq_selector_name',selectorName.value);LS.setItem('cdq_code',codeEditor.value);LS.setItem('cdq_selector',selectorEditor.value);LS.setItem('cdq_dep',deployment.value);setTopStatus('Réglages enregistrés.','ok')}
function loadSettings(){clientId.value=LS.getItem('cdq_client')||clientId.value;scriptId.value=LS.getItem('cdq_script')||'';codeName.value=LS.getItem('cdq_code_name')||'Code.gs';selectorName.value=LS.getItem('cdq_selector_name')||'Selecteur.html';codeEditor.value=LS.getItem('cdq_code')||'';selectorEditor.value=LS.getItem('cdq_selector')||'';description.value='Mise à jour CDQ - '+new Date().toLocaleString('fr-CA',{hour12:false});const b=readBackup();if(b)backupInfo.textContent='Sauvegarde : '+new Date(b.date).toLocaleString('fr-CA',{hour12:false});updateInstallState()}
async function loadProject(){if(!scriptId()){msg('Recherche automatique du projet Balance CDQ…');const found=await autoFindBalanceProject();if(!found)throw Error('Projet Balance CDQ introuvable automatiquement. Colle l’URL du projet Apps Script ou son Script ID.');scriptId.value=found.id;LS.setItem('cdq_script',found.id);setTopStatus('Projet trouvé : '+found.name,'ok')}msg('Lecture du projet…');const c=await getContent();const d=await getDeployments();deployment.innerHTML='<option value="">— Choisir le déploiement —</option>';for(const x of d.deployments||[]){const o=document.createElement('option');o.value=x.deploymentId;o.textContent=(x.deploymentConfig?.description||'Déploiement')+(x.deploymentConfig?.versionNumber?' • v'+x.deploymentConfig.versionNumber:'');deployment.appendChild(o)}const old=LS.getItem('cdq_dep');if(old&&[...deployment.options].some(o=>o.value===old))deployment.value=old;else if((d.deployments||[]).length===1)deployment.value=d.deployments[0].deploymentId;projectBadge.textContent='Projet : chargé';projectBadge.classList.add('ok');msg((c.files?.length||0)+' fichiers détectés.','ok')}
async function run(fn,start){try{msg(start);await fn()}catch(e){msg('Échec : '+e.message,'err');throw e}}
connect.onclick=()=>run(async()=>{await auth();authBadge.textContent='Google : connecté';authBadge.classList.add('ok');setTopStatus('Connexion Google réussie.','ok')},'Connexion Google…').catch(e=>setTopStatus(e.message,'err'));loadProject.onclick=()=>run(loadProject,'Lecture…').catch(()=>{});saveSettings.onclick=saveSettings;deployment.onchange=()=>LS.setItem('cdq_dep',deployment.value);
codeEditor.oninput=()=>LS.setItem('cdq_code',codeEditor.value);selectorEditor.oninput=()=>LS.setItem('cdq_selector',selectorEditor.value);pasteCode.onclick=async()=>{try{codeEditor.value=await navigator.clipboard.readText();LS.setItem('cdq_code',codeEditor.value)}catch{codeEditor.focus()}};pasteSelector.onclick=async()=>{try{selectorEditor.value=await navigator.clipboard.readText();LS.setItem('cdq_selector',selectorEditor.value)}catch{selectorEditor.focus()}};
replaceCode.onclick=()=>run(async()=>{if(!codeEditor.value.trim())throw Error('Code.gs vide.');await updateFiles(true,false);msg('Code.gs remplacé.','ok')},'Sauvegarde + remplacement…').catch(()=>{});replaceSelector.onclick=()=>run(async()=>{if(!selectorEditor.value.trim())throw Error('Sélecteur vide.');await updateFiles(false,true);msg('Sélecteur remplacé.','ok')},'Sauvegarde + remplacement…').catch(()=>{});replaceBoth.onclick=()=>run(async()=>{if(!codeEditor.value.trim()||!selectorEditor.value.trim())throw Error('Un des deux fichiers est vide.');await updateFiles(true,true);msg('Les 2 fichiers sont remplacés.','ok')},'Sauvegarde + remplacement…').catch(()=>{});
createVersion.onclick=()=>run(async()=>{const v=await createVersion();msg('Version '+v.versionNumber+' créée.','ok')},'Création de version…').catch(()=>{});deploy.onclick=()=>run(async()=>{const v=await createVersion();await deployVersion(v);msg('Version '+v.versionNumber+' créée et déployée.','ok')},'Création + déploiement…').catch(()=>{});oneClick.onclick=()=>run(async()=>{if(!codeEditor.value.trim()||!selectorEditor.value.trim())throw Error('Code.gs ou sélecteur vide.');await updateFiles(true,true);msg('Code envoyé. Création de version…');const v=await createVersion();msg('Version '+v.versionNumber+' créée. Déploiement…');await deployVersion(v);msg('TERMINÉ ✓ Version '+v.versionNumber+' déployée.','ok')},'1/3 Sauvegarde + remplacement…').catch(()=>{});
backup.onclick=()=>run(async()=>{const c=await getContent();saveBackup(c);msg('Sauvegarde créée.','ok')},'Sauvegarde…').catch(()=>{});downloadBackup.onclick=()=>{const b=readBackup();if(!b)return msg('Aucune sauvegarde.','err');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));a.download='CDQ_AppsScript_Backup.json';a.click()};restore.onclick=()=>run(async()=>{const b=readBackup();if(!b)throw Error('Aucune sauvegarde.');if(!confirm('Restaurer la dernière sauvegarde ?'))return;const cur=await getContent();saveBackup(cur);await gapi('/projects/'+encodeURIComponent(scriptId())+'/content',{method:'PUT',body:JSON.stringify({files:b.content.files})});msg('Sauvegarde restaurée.','ok')},'Restauration…').catch(()=>{});openScript.onclick=()=>window.open(scriptId()?'https://script.google.com/home/projects/'+encodeURIComponent(scriptId())+'/edit':'https://script.google.com/home','_blank');
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=b.dataset.tab==='code';codePanel.hidden=!c;selectorPanel.hidden=c});
function isStandalone(){return window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function updateInstallState(){if(isStandalone()){installState.textContent='✓ L’application est installée et ouverte en mode application.';installApp.textContent='Installée';installApp.classList.add('installed');installMain.textContent='APPLICATION INSTALLÉE';installMain.disabled=true}else{installState.textContent=installPrompt?'Prête à installer : touche INSTALLER L’APPLICATION.':'Si tu es déjà dans Chrome, touche INSTALLER L’APPLICATION. Si Chrome ne montre pas la fenêtre, utilise ⋮ > Installer l’application.'}}
async function doInstall(){if(isStandalone())return updateInstallState();if(installPrompt){installPrompt.prompt();const choice=await installPrompt.userChoice;installPrompt=null;if(choice.outcome==='accepted')installState.textContent='Installation acceptée ✓';else installState.textContent='Installation annulée.';return updateInstallState()}installHelp.hidden=false}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;updateInstallState()});window.addEventListener('appinstalled',()=>{installPrompt=null;updateInstallState()});installApp.onclick=doInstall;installMain.onclick=doInstall;closeInstall.onclick=()=>installHelp.hidden=true;installHelp.onclick=e=>{if(e.target===installHelp)installHelp.hidden=true};

/* V21.56 — réparation automatique Balance CDQ depuis Android. */
const CDQ_WORKING_DEPLOYMENT='AKfycbzZt5zgKLJA3FlRXgJOqR8OLopFBkCg8vapy4fLMNM37rlrYv0U__p8V22O_QAq5gk';
async function cdqRepairBalance(){
  await auth();authBadge.textContent='Google : connecté';authBadge.classList.add('ok');
  if(!scriptId()){
    msg('Recherche automatique du projet Balance CDQ…');
    const found=await autoFindBalanceProject();
    if(!found)throw Error('Je n’ai pas trouvé automatiquement le projet Balance CDQ. Colle l’URL du projet Apps Script ou son Script ID puis retouche le bouton.');
    scriptId.value=found.id;LS.setItem('cdq_script',found.id);setTopStatus('Projet trouvé automatiquement : '+found.name,'ok');
  }
  msg('1/5 Lecture et sauvegarde du projet…');
  const cur=await getContent();saveBackup(cur);
  if(!cur.files?.some(f=>f.type==='JSON'&&f.name==='appsscript'))throw Error('appsscript.json introuvable : ce projet ne semble pas être Balance CDQ.');
  const r=await fetch('./patch-v21-56.html?v=2',{cache:'no-store'});if(!r.ok)throw Error('Correctif V21.56 introuvable.');const patch=await r.text();
  const files=JSON.parse(JSON.stringify(cur.files));
  const html=files.filter(f=>f.type==='HTML');
  let sel=html.find(f=>/selector|selecteur/i.test(f.name||''));
  if(!sel)sel=html.find(f=>String(f.source||'').includes('adminModalOverlay')&&String(f.source||'').includes('displayModeButton'));
  if(!sel)throw Error('Sélecteur Balance CDQ introuvable dans le projet.');
  msg('2/5 Application du scroll et du partage…');
  let source=String(sel.source||'');
  source=source.replace(/<!-- CDQ V21\.56 SCROLL\+PARTAGE START -->[\s\S]*?<!-- CDQ V21\.56 SCROLL\+PARTAGE END -->/g,'');
  const i=source.toLowerCase().lastIndexOf('</body>');source=i>=0?source.slice(0,i)+patch+'\n'+source.slice(i):source+'\n'+patch;sel.source=source;
  CDQ.content=await gapi('/projects/'+encodeURIComponent(scriptId())+'/content',{method:'PUT',body:JSON.stringify({files})});
  msg('3/5 Recherche du déploiement fonctionnel…');
  const ds=await getDeployments();
  deployment.innerHTML='<option value="">— Choisir le déploiement —</option>';for(const x of ds.deployments||[]){const o=document.createElement('option');o.value=x.deploymentId;o.textContent=(x.deploymentConfig?.description||'Déploiement')+(x.deploymentConfig?.versionNumber?' • v'+x.deploymentConfig.versionNumber:'');deployment.appendChild(o)}
  let dep=(ds.deployments||[]).find(x=>x.deploymentId===CDQ_WORKING_DEPLOYMENT);
  const savedDep=LS.getItem('cdq_dep');if(!dep&&savedDep)dep=(ds.deployments||[]).find(x=>x.deploymentId===savedDep);
  if(!dep&&(ds.deployments||[]).length===1)dep=ds.deployments[0];
  if(!dep)throw Error('Le déploiement fonctionnel n’a pas été trouvé automatiquement. Choisis-le dans la liste puis retouche le bouton de réparation.');
  deployment.value=dep.deploymentId;LS.setItem('cdq_dep',dep.deploymentId);description.value='Balance CDQ V21.56 — scroll Android + partage installation';
  msg('4/5 Création de la nouvelle version…');const v=await createVersion();
  msg('5/5 Mise à jour du déploiement existant…');await deployVersion(v);
  const after=await getDeployments();const confirmed=(after.deployments||[]).find(x=>x.deploymentId===dep.deploymentId);
  if(!confirmed||Number(confirmed.deploymentConfig?.versionNumber)!==Number(v.versionNumber))throw Error('Google n’a pas confirmé la nouvelle version du déploiement.');
  projectBadge.textContent='Projet : réparé';projectBadge.classList.add('ok');
  msg('TERMINÉ ✓ Version '+v.versionNumber+' déployée sur le lien existant. Ferme puis rouvre Balance CDQ deux fois.','ok');
  repairInfo.textContent='✓ Scroll Affichage + Utilisateurs et partage d’installation rétablis — version '+v.versionNumber;
}
repairCdq.onclick=()=>run(cdqRepairBalance,'Préparation de la réparation…').catch(()=>{});

loadSettings();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=7').then(()=>setTopStatus('Application chargée. Utilise Chrome pour l’installation et Google.')).catch(e=>setTopStatus('Service d’installation : '+e.message,'err'));