'use strict';
const $=id=>document.getElementById(id),LS=localStorage;
const S={id:'',meta:null,files:[],draft:new Map(),pkg:new Map(),sel:'',install:null};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const key=f=>`${f.type}:${String(f.name).toLowerCase()}`,clone=x=>JSON.parse(JSON.stringify(x||[]));
const cid=()=>clientId.value.trim(),sid=()=>normalizeScriptId(S.id||scriptIdInput.value||projectSelect.value);
const stat=(t,k='')=>{status.textContent=t;status.className=`status bottom-status ${k}`.trim()},topstat=(t,k='')=>{topStatus.textContent=t;topStatus.className=`status ${k}`.trim()};
const badge=(id,t,k='')=>{const e=$(id);e.textContent=t;e.className=`badge ${k}`.trim()};
const nlabel=()=>new Date().toLocaleString('fr-CA',{hour12:false});
function settings(){LS.setItem('cdqsm_client_id',cid());LS.setItem('cdqsm_script_id',sid());LS.setItem('cdqsm_description',description.value);LS.setItem('cdqsm_deployment',deployment.value)}
function bootSettings(){clientId.value=LS.getItem('cdqsm_client_id')||clientId.value;scriptIdInput.value=LS.getItem('cdqsm_script_id')||'';description.value=LS.getItem('cdqsm_description')||`Mise à jour CDQ - ${nlabel()}`}
function backups(){try{return JSON.parse(LS.getItem('cdqsm_backups')||'[]')}catch{return[]}}
function saveBackup(id,content,label='Sauvegarde automatique'){const a=backups();a.unshift({date:new Date().toISOString(),scriptId:id,label,content});LS.setItem('cdqsm_backups',JSON.stringify(a.slice(0,12)));renderBackups()}
function renderBackups(){const a=backups();backupList.innerHTML=a.length?a.map((b,i)=>`<div class="backup-item"><div><b>${esc(b.label)}</b><span>${esc(new Date(b.date).toLocaleString('fr-CA',{hour12:false}))} • ${esc(b.scriptId)}</span></div><button data-r="${i}">Restaurer</button></div>`).join(''):'<div class="empty">Aucune sauvegarde locale.</div>';backupList.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>restore(Number(b.dataset.r)))}
async function restore(i){const b=backups()[i];if(!b||!confirm('Restaurer cette sauvegarde ?'))return;try{const cur=await getProjectContent(b.scriptId,cid());saveBackup(b.scriptId,cur,'Avant restauration');await updateProjectContent(b.scriptId,b.content.files,cid());scriptIdInput.value=b.scriptId;await loadProject(b.scriptId,false);stat('Sauvegarde restaurée ✓','ok')}catch(e){stat('Échec : '+e.message,'err')}}
async function connect(){try{topstat('Ouverture de Google…');await requestGoogleToken(cid(),true);badge('authBadge','Google : connecté','ok');await refreshProjects()}catch(e){badge('authBadge','Google : non connecté');topstat('Connexion impossible : '+e.message,'err')}}
function disconnect(){revokeGoogleToken();badge('authBadge','Google : non connecté');topstat('Session Google déconnectée.')}
async function refreshProjects(){try{topstat('Lecture des projets Apps Script…');const d=await listAppsScriptProjects(cid()),a=d.files||[];projectSelect.innerHTML='<option value="">— Choisir un projet —</option>'+a.map(f=>`<option value="${esc(f.id)}">${esc(f.name||'Sans titre')} • ${esc(new Date(f.modifiedTime).toLocaleString('fr-CA',{hour12:false}))}</option>`).join('');const old=normalizeScriptId(LS.getItem('cdqsm_script_id')||'');if(a.some(f=>f.id===old))projectSelect.value=old;badge('authBadge','Google : connecté','ok');topstat(`${a.length} projet(s) trouvé(s).`,'ok')}catch(e){topstat('Impossible de charger les projets : '+e.message,'err')}}
async function loadProject(id,save=true){id=normalizeScriptId(id);if(!id)throw Error('Choisis un projet ou colle son Script ID.');stat('Lecture du projet…');const [m,c,d]=await Promise.all([getProjectMetadata(id,cid()),getProjectContent(id,cid()),listDeployments(id,cid()).catch(()=>[])]);S.id=id;S.meta=m;S.files=clone(c.files);S.draft.clear();S.pkg.clear();S.sel='';scriptIdInput.value=id;if(save)LS.setItem('cdqsm_script_id',id);projectMeta.innerHTML=`<b>${esc(m.title||'Projet Apps Script')}</b><br>Script ID : <code>${esc(id)}</code>`;badge('projectBadge','Projet : '+(m.title||'chargé'),'ok');renderFiles();renderDiff();renderDeps(d);stat(`${S.files.length} fichier(s) chargé(s).`,'ok')}
async function loadSelected(){try{await loadProject(projectSelect.value||scriptIdInput.value)}catch(e){stat('Échec : '+e.message,'err')}}
const baseFile=()=>S.files.find(f=>key(f)===S.sel);
function sourceOf(f){const k=key(f);return S.draft.get(k)?.source??S.pkg.get(k)?.source??f.source??''}
function renderFiles(){if(!S.files.length){fileTabs.innerHTML='<span class="empty">Charge un projet pour voir ses fichiers.</span>';fileEditor.value='';return}const changed=new Set([...S.draft.keys(),...S.pkg.keys()]);fileTabs.innerHTML=S.files.map(f=>`<button class="file-tab ${S.sel===key(f)?'active':''} ${changed.has(key(f))?'changed':''}" data-k="${esc(key(f))}">${esc(displayNameForFile(f))}</button>`).join('');fileTabs.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>selectFile(b.dataset.k));if(!S.sel)selectFile(key(S.files[0]));else{const f=baseFile();if(f)fileEditor.value=sourceOf(f)}}
function selectFile(k){S.sel=k;const f=baseFile();fileEditor.value=f?sourceOf(f):'';renderFiles()}
function draftCurrent(){const f=baseFile();if(!f)return;const k=key(f),src=fileEditor.value;if(src===(f.source||''))S.draft.delete(k);else S.draft.set(k,{name:f.name,type:f.type,source:src,displayName:displayNameForFile(f)});renderFiles();renderDiff()}
function revert(){const f=baseFile();if(!f)return;S.draft.delete(key(f));S.pkg.delete(key(f));fileEditor.value=f.source||'';renderFiles();renderDiff()}
function parsePackage(text){const s=String(text||'').replace(/\r\n/g,'\n'),re=/^\s*===\s*FILE\s*:\s*(.+?)\s*===\s*$/gmi,m=[...s.matchAll(re)];if(!m.length)throw Error('Aucun marqueur « === FILE: nom.ext === » trouvé.');return m.map((x,i)=>{const spec=apiNameFromDisplayName(x[1].trim());let src=s.slice(x.index+x[0].length,i+1<m.length?m[i+1].index:s.length).replace(/^\n/,'').replace(/\n$/,'');return{...spec,displayName:x[1].trim(),source:src}})}
function prepPackage(){try{if(!S.files.length)throw Error('Charge d’abord le projet.');const a=parsePackage(packageEditor.value);S.pkg.clear();a.forEach(e=>{const k=`${e.type}:${e.name.toLowerCase()}`;S.draft.delete(k);S.pkg.set(k,e)});packageResult.innerHTML=`<b>${a.length} fichier(s) préparé(s)</b><br>${a.map(x=>esc(x.displayName)).join(' • ')}`;renderFiles();if(S.pkg.has(S.sel))fileEditor.value=S.pkg.get(S.sel).source;renderDiff();stat('Package préparé. Vérifie avant d’écrire.','ok')}catch(e){packageResult.textContent=e.message;stat('Package invalide : '+e.message,'err')}}
function changes(){const m=new Map(S.draft);for(const [k,v]of S.pkg)m.set(k,v);return m}
const lines=s=>String(s||'').split('\n').length;
function renderDiff(){const a=[];for(const[k,e]of changes()){const b=S.files.find(f=>key(f)===k);if(!b||(b.source||'')!==e.source)a.push({e,b})}badge('changeBadge','Modifications : '+a.length,a.length?'warn':'');diffList.innerHTML=a.length?a.map(x=>`<div class="diff-item"><div class="diff-head"><span class="diff-name">${esc(x.e.displayName||displayNameForFile(x.e))}</span><span class="diff-kind ${x.b?'changed':'new'}">${x.b?'MODIFIÉ':'NOUVEAU'}</span></div><div class="diff-stats">Avant : ${lines(x.b?.source)} lignes • Après : ${lines(x.e.source)} lignes</div></div>`).join(''):'<div class="empty">Aucune modification préparée.</div>'}
function validate(){if(!S.id)throw Error('Aucun projet chargé.');let n=0;for(const[k,e]of changes()){const b=S.files.find(f=>key(f)===k);if(!b||(b.source||'')!==e.source)n++;if(e.type==='JSON')JSON.parse(e.source)}if(!n)throw Error('Aucune modification à écrire.');if(!S.files.some(f=>f.type==='JSON'&&f.name==='appsscript'))throw Error('appsscript.json absent. Écriture bloquée.');return n}
function build(fresh){const out=clone(fresh),m=changes();for(const[,e]of m){let f=out.find(x=>x.type===e.type&&String(x.name).toLowerCase()===String(e.name).toLowerCase());if(f)f.source=e.source;else out.push({name:e.name,type:e.type,source:e.source})}if(!out.some(f=>f.type==='JSON'&&f.name==='appsscript'))throw Error('appsscript.json absent après modification.');return out}
async function write(){const n=validate();stat('1/4 Relecture depuis Google…');const fresh=await getProjectContent(S.id,cid());stat('2/4 Sauvegarde complète…');saveBackup(S.id,fresh,`Avant écriture (${n} fichier${n>1?'s':''})`);stat('3/4 Écriture…');await updateProjectContent(S.id,build(fresh.files),cid());stat('4/4 Vérification…');const chk=await getProjectContent(S.id,cid());for(const[k,e]of changes()){const f=(chk.files||[]).find(x=>key(x)===k);if(!f||f.source!==e.source)throw Error('Vérification Google échouée pour '+(e.displayName||e.name))}S.files=clone(chk.files);S.draft.clear();S.pkg.clear();packageEditor.value='';packageResult.innerHTML='';renderFiles();renderDiff();settings();stat(`TERMINÉ ✓ ${n} fichier(s) écrit(s) et vérifié(s).`,'ok');return n}
function confirmWrite(){try{const n=validate();confirmText.textContent=`Tu vas modifier ${n} fichier(s) dans « ${S.meta?.title||'ce projet'} ». Une sauvegarde complète sera créée avant. Continuer ?`;confirmModal.hidden=false}catch(e){stat(e.message,'err')}}
function renderDeps(a){deployment.innerHTML='<option value="">— Choisir un déploiement existant —</option>'+a.map(d=>`<option value="${esc(d.deploymentId)}">${esc(d.deploymentConfig?.description||d.deploymentId)}${d.deploymentConfig?.versionNumber?' • v'+d.deploymentConfig.versionNumber:''}</option>`).join('');const old=LS.getItem('cdqsm_deployment');if(a.some(d=>d.deploymentId===old))deployment.value=old;else if(a.length===1)deployment.value=a[0].deploymentId}
async function version(){if(!S.id)throw Error('Charge d’abord un projet.');const v=await createProjectVersion(S.id,description.value.trim(),cid());stat('Version '+v.versionNumber+' créée.','ok');return v}
async function deploy(){if(!deployment.value)throw Error('Choisis le déploiement existant.');const dep=deployment.value,v=await createProjectVersion(S.id,description.value.trim(),cid());await updateDeployment(S.id,dep,v.versionNumber,description.value.trim(),cid());renderDeps(await listDeployments(S.id,cid()));deployment.value=dep;settings();stat(`Version ${v.versionNumber} créée et déployée ✓`,'ok')}
async function run(fn,start=''){try{if(start)stat(start);await fn()}catch(e){stat('Échec : '+e.message,'err')}}
function embedded(){const u=navigator.userAgent||'',r=document.referrer||'';browserWarning.hidden=!(/Android/i.test(u)&&(/; wv\)|FBAN|FBAV|Instagram/i.test(u)||/chatgpt|openai/i.test(r)))}
function standalone(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function installState(){installApp.textContent=standalone()?'Installée':'Installer';installApp.disabled=standalone()}
async function install(){if(standalone())return;if(S.install){S.install.prompt();await S.install.userChoice;S.install=null;installState()}else installModal.hidden=false}
connect.onclick=connect;disconnect.onclick=disconnect;refreshProjects.onclick=refreshProjects;projectSelect.onchange=()=>{if(projectSelect.value)scriptIdInput.value=projectSelect.value};loadProject.onclick=loadSelected;openScript.onclick=()=>window.open(sid()?`https://script.google.com/home/projects/${encodeURIComponent(sid())}/edit`:'https://script.google.com/home','_blank');
fileEditor.oninput=draftCurrent;saveDraft.onclick=()=>{draftCurrent();stat('Brouillon gardé.','ok')};revertFile.onclick=revert;copyFile.onclick=()=>navigator.clipboard.writeText(fileEditor.value).then(()=>stat('Code copié.','ok')).catch(()=>stat('Copie automatique impossible.','warn'));
pastePackage.onclick=()=>navigator.clipboard.readText().then(t=>{packageEditor.value=t;stat('Package collé.','ok')}).catch(()=>{packageEditor.focus();stat('Appuie longuement puis colle.','warn')});parsePackage.onclick=prepPackage;clearPackage.onclick=()=>{packageEditor.value='';packageResult.innerHTML='';S.pkg.clear();renderFiles();renderDiff()};validateChanges.onclick=()=>{try{stat(`Vérification réussie ✓ ${validate()} fichier(s) prêt(s).`,'ok')}catch(e){stat('Vérification : '+e.message,'err')}};writeChanges.onclick=confirmWrite;cancelWrite.onclick=()=>confirmModal.hidden=true;confirmWrite.onclick=()=>{confirmModal.hidden=true;run(write,'Écriture…')};
createVersion.onclick=()=>run(version,'Création de version…');deployVersion.onclick=()=>run(deploy,'Déploiement…');writeAndDeploy.onclick=()=>run(async()=>{await write();await deploy()},'Écriture + déploiement…');backupNow.onclick=()=>run(async()=>{const id=sid();if(!id)throw Error('Aucun projet.');saveBackup(id,await getProjectContent(id,cid()),'Sauvegarde manuelle');stat('Sauvegarde créée.','ok')},'Sauvegarde…');downloadBackup.onclick=()=>{const b=backups()[0];if(!b)return stat('Aucune sauvegarde.','warn');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));a.download='CDQ_AppsScript_Backup.json';a.click()};
deployment.onchange=settings;description.onchange=settings;scriptIdInput.onchange=settings;clientId.onchange=settings;installApp.onclick=install;closeInstall.onclick=()=>installModal.hidden=true;copyUrl.onclick=()=>navigator.clipboard.writeText(location.href).then(()=>topstat('Adresse copiée. Ouvre Chrome et colle-la.','ok')).catch(()=>topstat(location.href,'warn'));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.install=e;installState()});window.addEventListener('appinstalled',installState);
(async()=>{bootSettings();renderBackups();embedded();installState();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=8').catch(()=>{});try{await prepareGoogleClient(cid());connect.disabled=false;connect.textContent='Se connecter à Google';topstat('Application prête. Touche « Se connecter à Google ».')}catch(e){connect.disabled=false;connect.textContent='Réessayer Google';topstat(e.message,'err')}})();
